services:
  - type: web
    name: JobBoardPHPApp
    env: docker
    region: oregon # or your preferred region
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
